name: OHC Network - Zoom Drive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # runs every Sunday at 12:00 AM UTC
  workflow_dispatch:
    inputs:
      lookback_days:
        description: Number of days to keep Zoom meeting recordings
        required: false
        default: 7
      end_date:
        description: End date of Zoom meeting recordings to keep (YYYY-MM-DD)
        required: false
        default: '2023-06-28'
      delete_on_success:
        description: 'Delete recordings after uploading to Google Drive'
        required: true
        default: false

jobs:
  zoomdrive:
    runs-on: ubuntu-latest
    environment: Open Healthcare Network
    name: Download Zoom recordings and upload to Google Drive
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download Meetings from Zoom Cloud and Upload to Google Drive
        id: zoomdrive
        uses: coronasafe/zoomdrive@main
        with:
          zoom_account_id: ${{ secrets.ZOOM_ACCOUNT_ID }}
          zoom_client_id: ${{ secrets.ZOOM_CLIENT_ID }}
          zoom_client_secret: ${{ secrets.ZOOM_CLIENT_SECRET }}

          lookback_days: ${{ github.event.inputs.lookback_days }}
          end_date: ${{ github.event.inputs.end_date }}
          delete_on_success: ${{ github.event.inputs.delete_on_success }}

          gsa_credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          meeting_gdrive_folder_map: |
            {
              "85188928844": "1EPacfEi42rzBk24Yjc7a6M5mdJR7iUQE",
              "83105532335": "1TruJMh0JoizegqdAYVRhd217ZPOy49Bw",
              "84710625619": "1R6WvRV9Oq9906ZJpkKy9kdltNSg9R-6v",
              "default": "1AwBOj1Wt42x9TZJy1vKtD11aXicMNt_s"
            }
